config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'main/main'

  get 'profile/new'

  root 'fridges#home'
  resources :fridges
  
  
  get '/contactus' => 'home#contactus'
  get '/aboutus' => 'home#aboutus'
  get '/countries' => 'category#countries'
  
  get '/main' => 'main#main'
  get '/write' => 'main#write'
  post '/create' => 'main#create'

  
  get '/index' => 'main#index'
  get '/profile' => 'profile#profile'
  post '/profile/create' => 'profile#create'
  get '/profile/write' => 'profile#write'

  
  get 'auth/:provider/callback' => 'sessions#create'
  post 'logout' => 'sessions#destroy'
  get 'auth/failure' => 'sessions#failure'
  get 'auth/twitter', :as => 'login'

  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#login'
  
  get 'main/search' => "main#search"
  
  resources :recipes do
    collection do
      get :search
    end
  end
    
    
  resources :users do
    resources :profiles
    end
  end

app/models/fridge.rb
class Fridge < ActiveRecord::Base
    
    before_save :capitalize_title
    def capitalize_menu
        self.menu = self.menu.split(/\s+/).map(&:downcase).
            map(&:capitalize).join(' ')
    end
    
    def self.all_ratings ; %w[1 2 3 4 5] ; end
   validates :menu, :presence => true
   validates :ingredient, :presence => true
   validates :recipe, :presence => true
   validates :rating, :inclusion => {:in => Fridge.all_ratings}
   validates :where, :presence => true
   
end

f = Fridge.new(:menu => '', :ingredient => '', :recipe => '', :rating => '5', :where => 'Africa')

f.valid?    # => false
f.errors[:menu]
f.errors[:ingredient]
f.errors[:recipe]
f.errors.full_messages

app/models/fridgeuser.rb
class Fridgeuser < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    validates_presence_of :menu, :ingredient, :recipe, :country, :rate
    searchable do
        text :ingredient
    end
    
#    recipe = Recipe.where(recipes.country: "Asia");
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :profiles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usergoer.rb
class Usergoer < ActiveRecord::Base
    def self.create_with_omniauth(auth)
        Usergoer.create!(
            :provider => auth["provider"],
            :uid => auth["uid"],
            :name => auth["info"]["name"])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  
  before_filter :set_current_user
  protected # prevents method from being invoked by a route
  def set_current_user
    # we exploit the fact that the below query may return nil
    @current_user ||= Usergoer.where(:id => session[:user_id])
    redirect_to login_path and return unless @current_user
  end
  
  private
    def after_sign_in_path_for(resource)
      "/fridges"
    end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
    def countries
    end
end

app/controllers/fridges_controller.rb
class FridgesController < ApplicationController
    
    def home
    end
    
    def fridge_params
        params.require(:fridge).permit(:menu, :ingredient, :recipe, :rating, :where)
    end
    
    def show
        id = params[:id]
        @fridge = Fridge.find(id)
    end
    
    def index
        @fridges = Fridge.all
    end
    
    def new
        @fridge = Fridge.new
    end
    
    def create
        @fridge = Fridge.new(params[:movie])
        if @fridge.save
            flash[:notice] = "#{@fridge.menu} was created."
            redirect_to fridges_path
        else
            render 'new'
        end
        
        #@fridge = Fridge.create!(fridge_params)
        #flash[:notice] = "#{@fridge.menu} created!:D"
        #redirect_to fridges_path
    end
    
    def edit
        @fridge = Fridge.find params[:id]
    end
    
    def update
        @fridge = Fridge.find params[:id]
        if @fridge.update_attributes(params[:fridge])
            flash[:notice] = "#{@fridge.menu} was updated"
            redirect_to fridge_path(@fridge)
        else
            render 'edit'
        end
        
        #@fridge = Fridge.find params[:id]
        #@fridge.update_attributes!(fridge_params)
        #flash[:notice] = "#{@fridge.menu} updated! XD"
        #redirect_to fridge_path(@fridge)
    end
    
    def destroy
        @fridge = Fridge.find(params[:id])
        @fridge.destroy
        flash[:notice] = "#{@fridge.menu} deleted :'("
        redirect_to fridges_path
    end
    
    def contactus
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def contactus
  end
  
  def aboutus
  end
  
  def index
    unless user_signed_in?
      redirect_to "users/sign_in"
    end
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  
  def main
    redirect_to '/'
  end
  
  #def main
    # show all results
    #@recipes = Recipe.all
    #@ingredients = Ingredient.all
    
  #  if params[:country]
  #    @recipes = Recipe.where(:country => params[:country])
  #  else
  #    @recipes = Recipe.all
  #  end
    
    
  # end
  
  def profile
  end
  
  def write
  end
  
  
  def create
    recipe = Recipe.new
    recipe.menu = params[:menu]
    recipe.ingredient = params[:ingredient]
    recipe.recipe = params[:recipe]
    recipe.country = params[:country]
    recipe.rate = params[:rate]
    recipe.save
    
    redirect_to '/countries'
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user = current_user.email
  end
  
  def profile

    @profiles = Profile.all
  end
  
  def write
  end
  
  def create
    profile = Profile.new
    profile.username = params[:username]
    profile.usergender = params[:usergender]
    profile.country = params[:country]
    profile.preference = params[:preference]
    profile.useringredient = params[:useringredient]
    profile.save
    
    redirect_to '/profile'
  end
  
  def edit
    @profile = Profile.find params[:id]
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    
    def index
      if params[:country]
        @recipes = Recipe.where(:country => params[:country])
      else
        @recipes = Recipe.all
      end
    end
    
    def search
    @recipes = Recipe.search do
      keywords params[:query]
    end.results
    
    respond_to do |format|
      format.html { render :action => "index"}
      format.xml { render :xml => @recipes}
     end
    end


    #def main
    #  if params[:country]
    #    @recipes = Recipe.where(:country => params[:country])
    #  else
    #    @recipes = Recipe.all
    #  end
      
    #  redirect_to '/main'
    #end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_filter :set_current_user
    def create
        auth=request.env["omniauth.auth"]
        user=Usergoer.where(:provider => auth["provider"], :uid => auth["uid"]) ||
            Usergoer.create_with_omniauth(auth)
        session[:user_id] = user.ids
        redirect_to fridges_path
    end
    
    def destroy
        session.delete(:user_id)
        flash[:notice] = 'Logged out successfully'
        redirect_to '/'
        #fridges_path
    end
    
    def login
       render :partial => 'sessions/login' 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/fridge_helper.rb
module FridgeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/category/countries.html.erb
<html class='background'>

<button class='button span:after button1'>
<%= link_to "Africa", recipes_path(:country=>"Africa") %><br>
</button>

<button class='button span:after span button2'>
<%= link_to "Asia", recipes_path(:country=>"Asia") %><br>
</button>

<button class='button span:after span button3'>
<%= link_to "Austrailia/Oceania", recipes_path(:country=>"Austrailia/Oceania") %><br>
</button>

<button class='button span:after button4'>
<%= link_to "North America", recipes_path(:country=>"North America") %><br>
</button>

<button class='button span:after button5'>
<%= link_to "South America", recipes_path(:country=>"South America") %><br>
</button>

<button class='button span:after button6'>
<%= link_to "Europe", recipes_path(:country=>"Europe") %><br>
</button>


</html>
<!--
<a href='/main'>Africa</a><br>
<a href='/main'>Asia</a><br>
<a href='/main'>Austrailia/Oceania</a><br>
<a href='/main'>North America</a><br>
<a href='/main'>South America</a><br>
<a href='/main'>Europe</a>
-->

<!--
<a href='/main'>Africa</a><br>
%= link_to '/main', recipes_path(:country=>"Africa") %> 
<a href='/main'>Asia</a><br>
%= link_to '/main', recipes_path(:country=>"Asia") %><br>
<a href='/main'>Austrailia/Oceania</a>
%= link_to '/main', recipes_path(:country=>"Austrailia/Oceania") %><br>
<a href='/main'>North America</a>
%= link_to '/main', recipes_path(:country=>"North America") %><br>
<a href='/main'>South America</a>
%= link_to '/main', recipes_path(:country=>"South America") %><br>
<a href='/main'>Europe</a>
%= link_to '/main', recipes_path(:country=>"Europe") %><br>
-->

app/views/fridges/_fridge_form.html.haml
- unless @fridge.errors.empty?
  #warning
    Errors prevented this fridge from being #{fridges_controller}d:
    %%ul
      %li
        -@fridge.errors.full_messages.each do |error|
      %li = error

= label :fridge, :menu, 'Menu'
= text_field :fridge, 'menu'
  
= label :fridge, :ingredient, 'Ingredient; Please divide by comma'
= text_field :fridge, 'ingredient'
  
= label :fridge, :recipe, 'Recipe'
= text_field :fridge, 'recipe'

= label :fridge, :rating, 'Rating'
= select :fridge, :rating, ['1','2','3','4','5']

= label :fridge, :where, 'Continent'
  = select :fridge, :where, ['Africa','Asia','Austrailia/Oceania','Europe','North America', 'South America']

app/views/fridges/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Fridge

= form_tag fridge_path(@fridge), :method => :put do

  = label :fridge, :menu, 'Menu'
  = text_field :fridge, 'menu'
  
  = label :fridge, :ingredient, 'Ingredient; Please divide by comma'
  = text_field :fridge, 'ingredient'
  
  = label :fridge, :recipe, 'Recipe'
  = text_field :fridge, 'recipe'

  = label :fridge, :rating, 'Rating'
  = select :fridge, :rating, ['1','2','3','4','5']

  = label :fridge, :where, 'Continent'
  = select :fridge, :where, ['Africa','Asia','Austrailia/Oceania','Europe','North America', 'South America']

  = submit_tag 'Update Menu'
  
%h2 Edit Existing Fridge

= form_tag fridge_path(@fridge), :method => :put do

  = render :partial => 'fridge_form'
  = submit_tag 'Update Menu Info'

app/views/fridges/home.html.erb
<html class="backgroud">
<div>    
<h1>What's In My Fridge</h1>
<body>
<!--

<form method="get" action='/result'>
    Email:<input type="email" name="useremail"/><br>
    Password<input type="password" name="userpass"/><br>
</form>
-->
<div class=url1>
<a href='/aboutus' style="text-decoration:none">About us</a>
<a href='/contactus' style="text-decoration:none">Contact us</a>
<a href='/users/sign_in' style="text-decoration:none">Login</a>
</div>

</body>

</div>
</html>

app/views/fridges/index.html.erb
<html class='background1'>
<body style="background-color: #ce6839">
  

<div class='url3'>
  
<h2>Select How You Feel!</h2>
<table id="fridges">
  <thead>
    <tr></tr>
    <p class='border'>
  </thead>
  <%= link_to 'Go to my profile page', '/profile' %>
  <br/>

  <%= link_to 'Let me explore the world!', '/countries' %>
  <br/>
  </p>
</table>
</div>
  <%= link_to 'Log Out', '/users/sign_out' %>
  <br/>
  
</body>

</html>

app/views/fridges/new.html.haml
%h1 Create New Fridge

= form_tag fridges_path do

  = label :fridge, :menu, 'Menu'
  = text_field :fridge, 'menu'
  
  = label :fridge, :ingredient, 'Ingredient; Please divide by comma'
  = text_field :fridge, 'ingredient'
  
  = label :fridge, :recipe, 'Recipe'
  = text_field :fridge, 'recipe'

  = label :fridge, :rating, 'Rating'
  = select :fridge, :rating, ['1','2','3','4','5']

  = label :fridge, :where, 'Continent'
  = select :fridge, :where, ['Africa','Asia','Austrailia/Oceania','Europe','North America', 'South America']
  
  = submit_tag 'Save Changes'


%h2 Create New Fridge

= form_tag '/fridges', :method => :post do

  = render :partial => 'fridge_form'
  
  = submit_tag 'Save Changes'

app/views/fridges/show.html.haml
-# in app/views/fridge/show.html.haml

%h2 Details about #{@fridge.menu}

%ul#menu
  %li
    Rating:
    = @fridge.rating

%h3 Description:

%p#recipe= @fridge.recipe

= link_to 'Edit', edit_fridge_path(@fridge)
= button_to 'Delete', fridge_path(@fridge), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to Menu list', fridges_path

app/views/home/aboutus.html.erb
<div class='url2'>
<h2>About us</h2>

<p>This is a food suggestion app for those who are struggle in deciding what to eat for their meal from the ingredient they have.</p>

<a href='/' style="text-decoration:none"> Go back to Login page</a>
</div

app/views/home/contactus.html.erb
<div class='url2' >
<h2>Contact Us</h2>

<p>This app is intended for IT 484 group project from Minnesota State University Mankato</p>

<br>

<p>Email: sunkyeong.lee@mnsu.edu <br>
    raphael.morgan@mnsu.edu <br>
    tania.hasanpoor@mnsu.edu

</p>

<a href = '/' style="text-decoration:none">Go back to Login page</a>
</div>

app/views/main/main.html.erb
<h>search recipe: </h>
<%= form_tag search_recipes_path, :method => :get do%>
<%= text_field_tag :query, params[:query] %> <%= submit_tag "Search" %>
<% end %>
<br>


<% @recipes.each do |recipe| %>
<%=recipe.menu%>
<%=recipe.ingredient%>
<%=recipe.recipe%>
<%=recipe.country%>
<%=recipe.rate%>
<br>
<br>

<% end %>
<a href='/write'>Add recipe</a>
<br>
<a href='/profile'>Go to my profile</a>

app/views/main/write.html.erb
<h>Add recipe</h>
<br>
<form action="/create" method="post">
    Menu: <input type="text" name="menu"><br>
    Ingredient: <input type="text" name="ingredient"><br>
    Recipe: <input type="text" name="recipe"><br>
    country:
    <select name="country">
        <option value="Africa">Africa</option>
        <option value="Asia">Asia</option>
        <option value="Austrailia/Oceania">Austrailia/Oceania</option>
        <option value="North America">North America</option>
        <option value="South America">South America</option>
        <option value="Europe">Europe</option>
    </select><br>
    rate:
    <select name="rate">
        <option value=1>1</option>
        <option value=2>2</option>
        <option value=3>3</option>
        <option value=4>4</option>
        <option value=5>5</option>
    </select><br>
    <input type="submit"/>
</form>
<a href="/main"></a>

app/views/recipes/index.html.erb
<h>Nah I am just hungry: </h>
<%= form_tag search_recipes_path, :method => :get do%>
<%= text_field_tag :query, params[:query] %> <%= submit_tag "Search" %>
<% end %>

<br>
<br>
<br>
<% @recipes.each do |recipe| %>
<%=recipe.menu%><br>
<%=recipe.ingredient%><br>
<%=recipe.recipe%><br>
Category: <%=recipe.country%><br>
Rate: <%=recipe.rate%><br>
<br>
<% end %>

<a href='/write'>Add recipe</a>
<br>
<a href='/profile'>Go to my profile</a>